/*
 * Copyright (c) 2018, All Rights Reserved
 *
 * Written by Leonid Novikov <flint.emerald@gmail.com>
 */

package com.icodici.universa.contract;

import com.icodici.crypto.AbstractKey;

/**
 * Wrapper class for sequence of bytes, that was generated by {@link AbstractKey#createAnonymousId()}
 */
public class AnonymousId {

    private byte[] anonymousId;

    public AnonymousId(byte[] newValue) {
        this.anonymousId = newValue;
    }

    public static AnonymousId fromBytes(byte[] newValue) {
        return new AnonymousId(newValue);
    }

    public byte[] getBytes() {
        return this.anonymousId;
    }

}
